# -*- coding: utf-8 -*-
"""de-get_zipfiles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CmgK_AoczWRp2Ga26nGD4_HMkxd_q31o
"""

import requests
import zipfile

x = requests.get('https://test-manage.tcloud.gov.tw/gdp-backend-api/api/hpc/download',
                 params={"downloadPath": '/apiRecordLog/newst/最新產檔結果.zip',
                         'key': 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIvYXBpUmVjb3JkTG9nL25ld3N0L-acgOaWsOeUouaqlOe1kOaenC56aXAiLCJleHAiOjE2OTU4NjY1MTEsImlhdCI6MTY2NDMzMDUxMX0.g5lUdqeZmsBNDHkJGKWEImrAug1d3vV5WcqYKn2vmF0vPMGESCGJ0PBwsyX-HSKk1tbMsD35e_0U4K2fnPM5nw',
                         'iv':'1664330511092'
                         })

open('today.zip', 'wb').write(x.content)

with zipfile.ZipFile("/content/today.zip","r") as zip_ref:
    zip_ref.extractall()

with zipfile.ZipFile("/content/最新產檔結果.zip","r") as zip_ref:
    zip_ref.extractall()

"""送到storage"""

# Imports the Google Cloud client library
from google.cloud import storage
import os
# 這邊要吃api金鑰
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/drive/MyDrive/secret/tradeeven-file-tcloud-data-analysis.json"
storage_client = storage.Client()

#主要的fuction
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    """Uploads a file to the bucket."""
    # The ID of your GCS bucket
    # bucket_name = "your-bucket-name"
    # The path to your file to upload
    # source_file_name = "local/path/to/file"
    # The ID of your GCS object
    # destination_blob_name = "storage-object-name"

    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    blob.upload_from_filename(source_file_name)

    print(
        f"File {source_file_name} uploaded to {destination_blob_name}."
    )

from datetime import date
today = date.today()
filenm ='最新產檔結果_'+str(today)+'.zip'
print(filenm)

#測試上傳單一檔案，第一個參數是傳送位置(不動)，第二個是檔案路徑，第三個是檔案名稱
upload_blob('tradevan-to-iii','/content/最新產檔結果.zip','最新產黨結果_2022-09-29.zip')

"""Delete files"""

import os
directory_name = '/home/tcloud_iii_gcp/filestmp'
filetypels = ['.zip','.xlsx','.csv']
for file in os.listdir(directory_name):
  for typef in filetypels:
    if typef in file:
      zip_path = '/home/tcloud_iii_gcp/filestmp/'+file
      os.remove(zip_path)
print("files clear")