# -*- coding: utf-8 -*-
"""de-order.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OtxefIZYxcfkA6yZZRkOoTWNUAT2qDBz
"""

import pandas as pd
import requests
import zipfile

order = pd.read_csv('/content/drive/MyDrive/dataset/dataengineering/關於SME下單_2022_1003_03.csv', header='infer')
order = order[['統一編號', '公司名稱', '公司地址', '訂單日期', '訂單編號', '訂單狀態', '解決方案UUID', '解決方案中文名稱',
       '方案名稱', '方案價格', '使用點數', '自付額', '建立日期', '異動日期', '退還點數', '退回自付額', '請領狀態',
       '發票1查驗狀態', '發票2查驗狀態', '是否有評價', '方案期程', '合約起始日(起)', '合約起始日(迄)', '折讓單總金額',
       '折讓單日期', '不可核銷點數', '點數來源']]
order.head(5)

order.columns

order_col =['sme_ban',
'sme_name',
'sme_address',
'order_date',
'order_num',
'order_status',
'solution_uuid',
'solution_name',
'solution_spec',
'sol_price',
'sol_point',
'sol_selfpay',
'order_est_date',
'order_change_date',
'return_point',
'return_pay',
'reimburse_status',
'invoice_check1',
'invoice_check2',
'review_status',
'solution_duration',
'contract_start_date',
'contract_end_date',
'allowence_price',
'allowence_date',
'unreimbuse_point',
'point_source']

order.columns = order_col
order.head(5)

order.columns

order_basic = order[['sme_ban', 'sme_name', 'sme_address', 'order_date', 'order_num',
       'order_status', 'solution_uuid', 'solution_name', 'solution_spec',
       'sol_price', 'sol_point', 'sol_selfpay', 'order_est_date',
       'order_change_date', 'return_point', 'return_pay', 'solution_duration', 'contract_start_date', 'contract_end_date','point_source']]
order_further = order[['sme_ban','order_num','order_status', 'solution_uuid', 'solution_name','reimburse_status','invoice_check1', 'invoice_check2', 'review_status','allowence_price', 'allowence_date', 'unreimbuse_point']]

order_basic.to_csv('order_basic.csv')
order_further.to_csv('order_further.csv')

# Imports the Google Cloud client library
from google.cloud import storage
import os
# 這邊要吃api金鑰
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/drive/MyDrive/secret/tradeeven-file-tcloud-data-analysis.json"
storage_client = storage.Client()
#主要的fuction
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    """Uploads a file to the bucket."""
    # The ID of your GCS bucket
    # bucket_name = "your-bucket-name"
    # The path to your file to upload
    # source_file_name = "local/path/to/file"
    # The ID of your GCS object
    # destination_blob_name = "storage-object-name"

    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    blob.upload_from_filename(source_file_name)

    print(
        f"File {source_file_name} uploaded to {destination_blob_name}."
    )

upload_blob('tcloud_bq_files','/content/order_basic.csv','order_basic.csv')
upload_blob('tcloud_bq_files','/content/order_further.csv','order_further.csv')