# -*- coding: utf-8 -*-
"""de-points_monitor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PcCw9h39vM4wLGnQ_v08zNdWbyyTZ4i
"""

import requests
import json
import pandas as pd
import time
import os
from google.cloud import bigquery

point_mon = pd.read_excel('/content/drive/MyDrive/dataset/dataengineering/點數監控_20221005_2359.xlsx')
point_mon.head(5)

point_mon.columns

point_mon_col = ['budget_source',
'date',
'budget_in_total',
'cumul_sme',
'cumul_point_to_sme',
'cumul_sme_usedpt',
'pt_on_sme',
'return_sme_1m',
'return_point_1m',
'return_point_3m',
'cumul_unreimbuse_point',
'cumul_return_pt',
'real_sme',
'real_pt',
'real_sme_ptused',
'rest_pt',
'total_sale_price',
'cumul_reim_pt',
'culmul_reiming_pt',
'reimable_pt',
'unreimable_pt',
'ratio_reim_order',
'ratio_reim_order_done',
'ratio_apply_reim',
'total_pt_2nd',
'pt_ratio_2nd',
'ratio_2nd_pt_out',
'ratio_2nd_pt_rest']
point_mon.columns =point_mon_col
point_mon

point_mon['date']=pd.to_datetime(point_mon['date'])

credentials_path = '/content/drive/MyDrive/secret/tradeeven-file-tcloud-data-analysis.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credentials_path
client = bigquery.Client()
table_id = 'tcloud-data-analysis.tcloud_analytic_db.budget_monitor'
 
job = client.load_table_from_dataframe(point_mon, table_id)
job.result()  #等待寫入完成