# -*- coding: utf-8 -*-
"""de-reimburse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eil5VZuFTTKyJPnzIJ0G5p-ztOUjrUb
"""

import pandas as pd
import requests
import zipfile

reimburse = pd.read_excel('/content/drive/MyDrive/dataset/dataengineering/每日可核銷訂單清單_2022_1004_06.xlsx')
reimburse.head(5)

reimburse.columns

reim_col =['supplier_ban', 'sme_ban', 'order_num', 'order_status', 'reimburse_status', 'reimburse_num', 'contract_start_date', 'contract_end_date', 'solution_uuid', 'solution_name', 'solution_spec', 'solution_duration', 'sol_price', 'sol_point', 'sol_selfpay', 'return_point', 'return_pay',
'last_reim_point', 'now_reim_point', 'rest_point', 'receipt_status', 'reimburse_submit_date', 'reim_change_date', 'order_change_date', 'sme_name', 'supplier_name', 'reimburseful_date', 'solution_satisfaction', 'reviews', 'invoice1', 'invoice_check1', 'invoice2', 'invoice_check2', 'point_source',
'point_source_code', 'unreimbuse_point', 'invoice_date1', 'invoice_date2', 'invoice_price1', 'invoice_price2']
reimburse.columns =reim_col
reimburse.head(5)

reimburse.to_csv('reimburse.csv')

# Imports the Google Cloud client library
from google.cloud import storage
import os
# 這邊要吃api金鑰
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/drive/MyDrive/secret/tradeeven-file-tcloud-data-analysis.json"
storage_client = storage.Client()
#主要的fuction
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    """Uploads a file to the bucket."""
    # The ID of your GCS bucket
    # bucket_name = "your-bucket-name"
    # The path to your file to upload
    # source_file_name = "local/path/to/file"
    # The ID of your GCS object
    # destination_blob_name = "storage-object-name"

    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    blob.upload_from_filename(source_file_name)

    print(
        f"File {source_file_name} uploaded to {destination_blob_name}."
    )

upload_blob('tcloud_bq_files','/content/reimburse.csv','reimburse.csv')