# -*- coding: utf-8 -*-
"""file_to_gsc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ycjk6OzG9ik31_dR9DDX18FczFqhv-_A
"""

# Imports the Google Cloud client library
from google.cloud import storage
import os
# 這邊要吃api金鑰
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/drive/MyDrive/secret/tradeeven-file-tcloud-data-analysis.json"
storage_client = storage.Client()

#主要的fuction
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    """Uploads a file to the bucket."""
    # The ID of your GCS bucket
    # bucket_name = "your-bucket-name"
    # The path to your file to upload
    # source_file_name = "local/path/to/file"
    # The ID of your GCS object
    # destination_blob_name = "storage-object-name"

    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    blob.upload_from_filename(source_file_name)

    print(
        f"File {source_file_name} uploaded to {destination_blob_name}."
    )

#測試上傳單一檔案，第一個參數是傳送位置(不動)，第二個是檔案路徑，第三個是檔案名稱
upload_blob('tradevan-to-iii','/content/drive/MyDrive/dataset/關於SME下單_2022_0806_03.csv','關於SME下單_2022_0806_03.csv')

#傳送多檔，麻煩幫我修改成符合你們系統的格式
directory_name = '/content/drive/MyDrive/dataset'
for file in os.listdir(directory_name):
  if '.zip' in file:
    zip_path = '/content/drive/MyDrive/dataset/'+file
    upload_blob('tradevan-to-iii',zip_path,file)