# -*- coding: utf-8 -*-
"""get district from address.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z40wRSiUhF9GWW9TKkgqMiTnn7Qt1xsI
"""

import pandas as pd

town = pd.read_csv('/content/Taiwan_town-town.csv', header='infer')
town.head(5)

sme = pd.read_csv('/content/sme20220927_utf8.csv', header='infer')
sme.head(5)

sme_addr = sme[['統一編號','公司名稱','公司地址']]
sme_addr.head(5)

distr_ls = town['district_name'].tolist()
distr_ls

sme_addr['公司地址'][2]

for dis in distr_ls:
  if dis in sme_addr['公司地址'][2]:
    print(dis)

def addtodis(add):
  distls = distr_ls
  for dis in distls:
    if dis in add:
      return dis
    else:continue
    return 'notfound'

addtodis(sme_addr['公司地址'][3])

newls = []
for i in range(len(sme_addr)):
  newls.append(addtodis(sme_addr['公司地址'][i]))

sme_addr['鄉鎮市區']= newls

sme_addr.head(5)